version: '3.7'

services:
    php:
      &php
      working_dir: /app
      tty: true
      stdin_open: true
      environment:
        - HOME
        - COMPOSER_HOME=$HOME/.composer
      networks:
        - "traefik_proxy"
      volumes:
        - $HOME/.ssh:$HOME/.ssh:ro
        - $HOME/.composer:$HOME/.composer
        - $PWD:/app
        - $HOME/.symfony:$HOME/.symfony
      build:
        context: .docker/php/
        args:
            PHP_VERSION: '8.1.27-fpm-alpine'

    web:
      <<: *php
      entrypoint: ["symfony", "serve", "--no-tls", "--allow-http", "--port=8011"]
      ports:
        - 8011:80
      networks:
        - "traefik_proxy"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.template_web.rule=Host(`blog.ingatlan-local.com`)"
        - "traefik.http.routers.template_web.service=svc_template_web"
        - "traefik.http.services.svc_template_web.loadbalancer.server.port=8011"
      env_file:
        - .env

    mysql:
      image: 'mysql/mysql-server:8.0'
      ports:
          - '${FORWARD_DB_PORT:-3306}:3306'
      environment:
          MYSQL_ROOT_PASSWORD: 'secret'
          MYSQL_ROOT_HOST: "%"
          MYSQL_DATABASE: 'teszt'
          MYSQL_USER: 'admin'
          MYSQL_PASSWORD: 'admin123'
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
      volumes:
          - 'mysqlvolume:/var/lib/mysql'
      networks:
          - traefik_proxy
      healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
          retries: 3
          timeout: 5s
      env_file:
          - .env
                
networks:
  traefik_proxy:
    external: true

volumes:
  mysqlvolume:
    driver: local
