version: '3.7'

services:
    php:
      &php
      working_dir: /app
      tty: true
      stdin_open: true
      environment:
        - HOME
        - COMPOSER_HOME=$HOME/.composer
        - SSH_AUTH_SOCK=/ssh-auth.sock
      networks:
        - "traefik_proxy"
      volumes:
        - $SSH_AUTH_SOCK:/ssh-auth.sock
        - $HOME/.ssh:$HOME/.ssh:ro
        - $HOME/.composer:$HOME/.composer
        - $PWD:/app
        - $HOME/.symfony:$HOME/.symfony
      build:
        context: .docker/php/
        args:
            PHP_VERSION: '8.1.27-fpm-alpine'

    web:
      <<: *php
      entrypoint: ["symfony", "serve", "--no-tls", "--allow-http", "--port=8000"]
      ports:
        - 8000:80
      networks:
        - "traefik_proxy"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.template_web.rule=Host(`template.ingatlan-local.com`)"
        - "traefik.http.routers.template_web.service=svc_template_web"
        - "traefik.http.services.svc_template_web.loadbalancer.server.port=8000"

networks:
  traefik_proxy:
    external: true
